Repository Y3-S1-project-group/FieldExpert-Frontend, pull requests merged in 2024-10, with the labels that each got.

#6 Feature/special
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/index.css
  src/pages/CropForm.jsx
  src/pages/CropRecommendation.jsx
  src/pages/DiseaseDetection.jsx
  src/pages/Home.jsx
  src/pages/PestDetection.jsx
Labels: feature

#9 Feature/special
  package-lock.json
  src/App.jsx
  src/components/PlantDiseases/DiseaseDetectionComponent.jsx
  src/pages/CropForm.jsx
  src/pages/DiseaseDetection.jsx
  src/pages/PestDetection.jsx
Labels: feature

#10 Change the styles. Fixed the error happened in the API key
  package-lock.json
  package.json
  public/cropsell.png
  public/report.png
  src/App.css
  src/components/PlantDiseases/DiseaseDetectionComponent.jsx
  src/pages/CropRecommendation.jsx
  src/pages/DiseaseDetection.jsx
  src/pages/Home.jsx
  src/pages/PestDetection.jsx
Labels: bug

#16 Feature/special
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/index.css
  src/pages/CropRecommendation.jsx
  src/pages/Home.jsx
Labels: bug

#17 Feature/inventory management
  package-lock.json
  package.json
  src/App.jsx
  src/Styles/display.css
  src/Styles/footer.css
  src/components/AddInventory/AddInventory.jsx
  src/components/CustomDisplayInventory/CustomDisplayInventory.jsx
  src/components/DeleteInventory/DeleteInventory.jsx
  src/components/DisplayInventory/DisplayInventories.jsx
  src/components/Footer/Footer.jsx
  src/components/InventoryReport/InventoryReport.jsx
  src/components/UpdateInventory/UpdateInventory.jsx
  src/pages/AdminInventory/AdminInventory.jsx
  src/pages/ClientInventory/ClientInventory.jsx
  src/pages/Home.jsx
Labels: feature

#18 All functions are integrated
  src/pages/Home.jsx
Labels: bug

#20 Feature/special
  src/components/PlantDiseases/DiseaseDetectionComponent.jsx
  src/components/Sales/AddSales.jsx
  src/pages/CropRecommendation.jsx
  src/pages/PestDetection.jsx
Labels: issues fixed

#22 Feature/special
  src/Styles/footer.css
  src/components/Footer/Footer.jsx
  src/pages/CropRecommendation.jsx
  src/pages/PestDetection.jsx
Labels: enhancement
